Fix "Invalid revision range" error after force-push to master branch.

diff --git a/Oyafile b/Oyafile
--- a/Oyafile
+++ b/Oyafile
@@ -6,21 +6,24 @@ Changeset: |
   set -e
 
   crnt_branch=$(git rev-parse --abbrev-ref HEAD)
+  empty_tree=4b825dc642cb6eb9a060e54bf8d69288fbee4904
   if [[ "$crnt_branch" != "master" ]]; then
     # TODO: Make master configurable.
-    git branch --quiet -f master origin/master
-    compare_to=master
+    # git branch --quiet -f master origin/master
+    compare_to="origin/master"
   else
     last_sha_var="OYA_LAST_SUCCESS_SHA"
     last_sha="${!last_sha_var}"
     if [ -z "${last_sha}" ]; then
-      empty_tree=4b825dc642cb6eb9a060e54bf8d69288fbee4904
       compare_to=${empty_tree}
     else
+      git fetch -a
       compare_to=${last_sha}
     fi
   fi
-  diff_tree=$(git diff-tree ${compare_to}..HEAD)
+  # If fails --> set compare_to to empty_tree and re-run diff-tree
+  diff_tree=$(git diff-tree ${compare_to}..HEAD || (echo "Unable to calculate differences since the last build. Force-pushed to the default branch?"; git diff-tree ${empty_tree}..HEAD))
+
   # Directories only.
   changed_subdirs=$(echo "${diff_tree}" | awk '$1$2 ~ /04/' | cut -f2-)
   # Only files in root directory.
