Force a build error.

diff --git a/docker/Oyafile b/docker/Oyafile
--- a/docker/Oyafile
+++ b/docker/Oyafile
@@ -8,8 +8,16 @@ Values:
   image: bilus/oya-circleci
 
 
-Changeset: oya run circleci.Changeset
-
+Changeset: |
+  set -e  # TODO Failure in subtask doesn't fail circleci without it.
+  echo "Changeset task"
+  oya run circleci.Changeset
+  # Paths are relative to the git repository root,
+  # we need paths relative to the project root, i.e. /docker.
+  # global=$(oya run circleci.Changeset)
+  # if [[ "$global" =~ "\+/docker" ]]; then
+  #   echo "+/"
+  # fi
 
 onMerge: |
   set -e
